/**
 * @description       : 
 * @author            : D.Fujinohara
 * @group             : 
 * @last modified on  : 2025-04-16
 * @last modified by  : D.Fujinohara 
 * Modifications Log
 * Ver   Date         Author         Modification
 * 1.0   2025-04-16   D.Fujinohara   Initial Version
**/
public with sharing class DevOpsTest {
    public DevOpsTest() {
        System.debug('DevOpsTest');
    }
}